kind: Service
apiVersion: v1
metadata:
  name: redis-endpoint
spec:
  selector:
    app: redis
  ports:
    - name: service
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: cluster
      port: 16379
      targetPort: 16379
      protocol: TCP
